// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diabajuqtvuhibizywhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpYWJhanVxdHZ1aGliaXp5d2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MjQ4MTcsImV4cCI6MjA1MDUwMDgxN30.5mpMpW1P--iTnxWelz8PvlseBNBtOU-LFZ_M4CGLmOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);